### ISSUE TITLE
JSON-LD parsing

### ISSUE THREAD

**Issue by pietercolpaert** [openplannerteam/Itinero-Transit#1]
When the API is going to evolve, or when we are going to adopt other data sources, the JSON structure might not always look the way it does at graph.irail.be today. In order to fix this, we have linked the JSON structure to a context. This context allows to link all properties to their web identifiers.

Clients should evolve with the web API, but the API itself should always be backwards compatible to a certain extent with its past (e.g., still make sure clients can interpret the server up to the last major version).

In order to have  a more loose contract between clients and servers, we introduce Linked Data: instead of relying on the structure of what the server gives us, we’re first going to parse all the data as triples, and then going to query that structure for exactly the frame the rest of our program can work with.

## Solution

Use a higher level library to parse the JSON into RDF Triples. I do not have experience with this library myself, but have found this one: https://www.nuget.org/packages/json-ld.net/

I suppose it should have a function toRDF somewhere that allows you to use the triples, and recreate the triples from there.

**Comment by pietervdvn** [comment]
By now, the library uses our own fork of [Json-ld](https://github.com/openplannerteam/json-ld.net) which is heavily refactored.

It does not work with triples, but by using the fully expanded keys for the relations, the client should be robust enough for future changes.
