### ISSUE TITLE
Migrate to netstandard2.0

### ISSUE THREAD

**Issue by xivk** [openplannerteam/itinero-transit#16]
It's best practice to use `netstandard2.0` instead of `netcoreapp2.0` when publishing libraries:

https://github.com/openplannerteam/itinero-transit/blob/master/src/Itinero.Transit/Itinero.Transit.csproj#L20

Think of `netstandard2.0` as cross-platform and `netcoreapp2.0` .NET core only.

**Comment by pietervdvn** [comment]
I've manually changed the target framework in 'Itinero.Transit.csproj', then I fixed the build errors in rider.

Can you do a small check if that was all that had to happen?

(PS: I only saw that you self-assigned after I already fixed it)

**Comment by xivk** [comment]
No worries, I have no idea why I self-assigned ;-)

**Comment by xivk** [comment]
Looks OK btw :+1:
