### ISSUE TITLE
Client-side headers

### ISSUE THREAD

**Issue by pietercolpaert** [openplannerteam/Itinero-Transit#2]
https://github.com/openplannerteam/Itinero-Transit/blob/master/Itinero-Transit/LinkedData/Downloader.cs#L48

 * [ ] I would change the user-agent to an Itinero specific one
 * [ ] I would add another header that always asks for application/ld+json, as other formats may become supported in the future: `accept: application/ld+json`

**Comment by pietervdvn** [comment]
Headers have been added
