### ISSUE TITLE
Implement transitdb

### ISSUE THREAD

**Issue by xivk** [openplannerteam/itinero-transit#24]
Implement a transit db, one concept `TransitDb` that contains a `ConnectionsDb`, `TripsDb` and `StopsDb`. Make this serializable.

**Comment by pietervdvn** [comment]
I merged in the 'IO-cleanup' code and did a few updates here and there. There is a new callback added which can be injected into the constructor to update a certain timeframe. The server has been based on this new version.

I also noticed that, when loading more data in multiple batches, the departure enumerator fails and can not enumerate entries anymore - this is something that should be looked into. I've added a failing functional test for this specific case.
