### ISSUE TITLE
Implement updating transitdb based on routing algorithms

### ISSUE THREAD

**Issue by xivk** [openplannerteam/itinero-transit#29]
We need to implement a way for any of the routing algorithms to request extra data from the transit db when they need it.

- Implement a way to mark data as requested.
- Have the synchronization mechanism respond to this.
- Notify the running algorithm once this is completed.

**Comment by pietervdvn** [comment]
Already there:
Via 'profileExtensions', the profile uses 'transitDb.updateTimeWindow'. This is turns calls a callback, which is provided by the user of the library. The callback will then load the requested data (or at least: fill the gaps between them).
Once this callback is completed, the core algos will be run.
