### ISSUE TITLE
Implement an active synchronization mechanism

### ISSUE THREAD

**Issue by xivk** [openplannerteam/itinero-transit#30]
This module should be able to work in two ways:

- Loading all data into the transitdb for a given time-period.
- Have the transitdb fill based on requests.

The two combined should also be possible:

- Make sure we 'cache' the data in the transidb that is being requested. 

The first version we have to implement is a synchronization mechanism where we keep the transidb up-to-date for a specified time-period.

**Comment by pietervdvn** [comment]
Implemented in the server: see https://github.com/anyways-open/itinero-transit-server/commit/4ecc57c5d7c59708a61cc098b7dea1234d871c41

**Comment by xivk** [comment]
We should implement this here, reopening. This is not urgent just listing what needs to happen before release.

**Comment by pietervdvn** [comment]
Yeah, you are right. I could move the class which reloads to this repo

**Comment by pietervdvn** [comment]
Implemented, tested, documented.
