### ISSUE TITLE
Non optimal trips shown

### ISSUE THREAD

**Issue by xivk** [openplannerteam/itinero-transit#45]
![2019-03-07 21 02 25](https://user-images.githubusercontent.com/1128068/54023403-c81bc200-418c-11e9-8987-786a2e74dcee.jpg)

There are two cases here:

- Same departure time but different arrival time.
- Same arrival time but different departure time.

This could be acceptable if the # of transfers is different but those tradeoffs should be in the user profile. We should build a default that approaches the current routeplanners and give reasonable default results.

**Comment by pietervdvn** [comment]
Could you please provide the search query?

And are the number of transfers the same on both trips? If they are, this is clearly a bug.

This will need #37 to be fixed first

**Comment by pietervdvn** [comment]
Has been taken care of by #44 

Note: I'm gonna keep the 'same arrival time'-journeys; if the traveler misses his direct train, they know they still can take a later train with transfers (although this should become a profile preference too)
