### ISSUE TITLE
Add the catalog

### ISSUE THREAD

**Issue by pietervdvn** [openplannerteam/itinero-transit#68]
https://openplanner.ilabt.imec.be/catalog/

**Comment by xivk** [comment]
This is awesome! :+1:

**Comment by pietervdvn** [comment]
Hmmm, I now remember that those catalogs do not contain everything from belgium. For that, there is some turtle file available, but we don't have a parser for that.

Anyway, for now I have bigger issues then this, but it is on the backlog.

**Comment by pietervdvn** [comment]
Superseded by appsettings
