### ISSUE TITLE
GTFS

### ISSUE THREAD

**Issue by hypervtechnics** [openplannerteam/itinero-transit#76]
Based on some closed issues I assume there is support for GTFS as a data source. Is it really implemented? I could not find any files related to it.

**Comment by xivk** [comment]
No this is not implemented, could be a while before we get to that. If it fits our roadmap we will eventually but I'm not sure at the moment when that could be.

**Comment by pietercolpaert** [comment]
@hypervtechnics Probably the best way to go is publish a Linked Connections API from a GTFS using these scripts: https://github.com/linkedconnections/linked-connections-server. Itinero-transit can then sync with this server when configured with the entry URL
